const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[],network=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
await page.goto(require('node:url').pathToFileURL(require('node:path').join(__dirname,'../index.html')).href);
await page.click('#loadSample');await page.click('#analyzeSampleBtn');
assert.equal(await page.locator('#kTotal').textContent(),'$2,220,000');
assert.equal(await page.locator('#contradictionLedger article').count(),7);
assert.equal(await page.locator('.ledger-entry').count(),14);
assert.equal(await page.locator('#proofQueue article').count(),8);
assert.equal(await page.locator('#dealList').getByText('Recommended action',{exact:true}).count(),0);
const proofAudit=await page.locator('#proofQueue').innerHTML();
const audit=await page.locator('#waterfall').innerHTML();
await page.selectOption('#filterStatus','Assumption Dependent');await page.selectOption('#filterContradictions','Critical');
assert.equal(await page.locator('#dealList > .deal').count(),5);
assert.equal(await page.locator('#kExposed').textContent(),'$1,415,000');
assert.equal(await page.locator('#waterfall').innerHTML(),audit);assert.equal(await page.locator('#proofQueue').innerHTML(),proofAudit);
const downloadPromise=page.waitForEvent('download');await page.click('#downloadBtn');const download=await downloadPromise;
const fs=require('node:fs');const csv=fs.readFileSync(await download.path(),'utf8');assert(csv.includes('Highest Contradiction Severity'));assert(csv.includes('Next Proof Required'));assert(csv.includes('Additional Blocking Proof Count'));assert.equal(csv.split('\n').length,13);
await page.locator('#proofQueue article').first().evaluate(el=>el.scrollIntoView({behavior:'instant',block:'start'}));await page.screenshot({path:'/tmp/cairn-desktop.png'});
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#proofQueue article').first().evaluate(el=>el.scrollIntoView({behavior:'instant',block:'start'}));await page.screenshot({path:'/tmp/cairn-mobile.png'});
await page.click('#reset');assert(await page.locator('#results').isHidden());assert.equal(await page.locator('#filterContradictions').inputValue(),'All');
const uploaded='Custom Name,Amount,Stage,Forecast Category,Close Date\nUploaded Deal,300000,Negotiation,Commit,2020-01-01';
await page.setInputFiles('#fileInput',{name:'pipeline.csv',mimeType:'text/csv',buffer:Buffer.from(uploaded)});
await page.locator('#mappingSection').waitFor({state:'visible'});
assert.equal(await page.locator('[data-key="amount"]').inputValue(),'Amount');
await page.selectOption('[data-key="name"]','Custom Name');await page.click('#analyzeBtn');
assert.equal(await page.locator('#dealList .deal-name').textContent(),'Uploaded Deal');
assert((await page.locator('#contradictionLedger').textContent()).includes('Open opportunity has a past close date'));
assert(await page.locator('#demoResultsLabel').isHidden());
await page.click('#reset');
await page.evaluate(()=>{const dt=new DataTransfer();dt.items.add(new File(['Opportunity Name,Amount,Stage,Close Date\nDropped Deal,100,Discovery,2030-01-01'],'drop.csv',{type:'text/csv'}));document.querySelector('#dropZone').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}))});
await page.locator('#mappingSection').waitFor({state:'visible'});await page.click('#analyzeBtn');
assert.equal(await page.locator('#dealList .deal-name').textContent(),'Dropped Deal');
assert.equal(await page.locator('#kContradictions').textContent(),'0');assert.equal(await page.locator('.contradiction-callout').count(),0);
assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
assert.deepEqual(network,[]);assert.deepEqual(errors,[]);
console.log('Browser checks passed: demo, filters, full CSV, desktop/mobile overflow, reset, upload, auto/manual mapping, drag/drop, empty ledger, no network/storage, no console errors.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
